// LanguageProvider.tsx
"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "am";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hospital Names
    "hospital.name.full": "Adinas General Hospital",
    "hospital.name.short": "Adinas Hospital",
    "hospital.name.general": "General Hospital",
    "hospital.name.adinas": "Adinas",
    "hospital.name.afilas": "Adinas",

    // Navigation & Topbar
    "nav.home": "Home",
    "nav.hospital": "Hospital",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.service": "Services",
    "nav.services": "Services",
    "nav.blog": "Blog",
    "nav.about_us": "About Us",
    "nav.contact_emergency": "Contact & Emergency",
    "nav.toggle_menu": "Toggle navigation",
    "topbar.emergency_available": "Emergency Care Available 24/7",
    "topbar.call": "Call:",
    "cta.emergency_call": "Emergency Call",
    "cta.book_appointment": "Book Appointment",

    "nav.selected": "Selected",
    "nav.menu": "Menu",
    "nav.quick_links": "Quick Links",
    "nav.doctors": "Doctors",
    "nav.account": "Account",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.book": "Book",
    "nav.book_services": "Book Services",
    "nav.book_hospital_desc": "Book at Adinas General Hospital",
    "nav.book_appointment": "Book at Adinas General Hospital",  // Added this line
    "nav.branch_links": "Branch Links",

    // Hero Section
    "hero.headline": "Welcome to Adinas General Hospital",
    "hero.subheadline": "Excellence in healthcare services — from advanced clinical care to specialized medical treatments.",
    "hero.find_doctor": "Find a Doctor",
    "hero.hospital_subtitle": "24/7 Patient Care",
    "hero.welcome": "Welcome to Adinas General Hospital",
    "hero.description": "We are committed to providing exceptional healthcare services with compassion, innovation, and excellence. Our dedicated team of medical professionals ensures the highest quality care for every patient.",
    "hero.book_appointment": "Book Appointment",

    // General Hospital Section
    "general.title": "Adinas General Hospital",
    "general.hospital": "General Hospital",
    "general.subtitle": "Compassionate, specialized patient care available 24/7.",
    "general.feature1": "Over 10 specialty centers under one roof",
    "general.feature2": "State-of-the-art diagnostic and therapeutic care",
    "general.feature3": "Convenient one-stop medical center",
    "general.feature4": "Private hospital with high-quality standards",
    "general.feature5": "Experienced medical professionals",
    "general.location": "Location",
    "general.location_address": "Addis Ababa, Ethiopia",
    "general.emergency_services": "Emergency Services",
    "general.emergency_desc": "24/7 Emergency Care & Ambulance Services",
    "general.cta": "Discover Our Services",
    "general.why_choose_us": "Why Choose Us?",
    "general.why_choose_1": "Medical excellence with highly experienced specialists.",
    "general.why_choose_2": "Comprehensive Care - A full range of medical services.",
    "general.why_choose_3": "Advanced Technology - State-of-the-art medical equipment.",
    "general.why_choose_4": "Patient-Centered Approach - Compassionate, personalized care.",
    "general.why_choose_5": "24/7 Availability - Emergency and critical care services.",
    "general.why_choose_6": "High-Quality Facilities - Modern inpatient rooms and ICUs.",
    "general.hospital_description": "Our hospital has been delivering compassionate, expert medical care to our community. Our legacy of excellence is built on experience, innovation, and an unwavering commitment to patient well-being.",
    "general.learn_more": "Learn More",

    // Doctor Finder Section - Added translations
    "doctors.hero.badge": "Find a Doctor",
    "doctors.hero.title": "Our Expert Doctors",
    "doctors.hero.subtitle": "Connect with experienced specialists across key medical disciplines.",
    "doctors.headline": "Find a Doctor",
    "doctors.subtitle": "Connect with experienced specialists across key medical disciplines.",
    "doctors.filter_specialty": "Select Specialty",
    "doctors.filter_availability": "Select Availability",
    "doctors.filter_search": "Search Doctor by Name...",
    "doctors.view_all": "View All Specialists & Schedule",
    "doctors.book": "Book Appointment",
    "doctors.email": "Email",
    "doctors.available": "Available",
    "doctors.status_loading": "Loading...",
    "doctors.status_offline": "Offline Mode",
    "doctors.status_live": "Live Data",
    "doctors.no_doctors": "No doctors found matching your criteria.",

    // About Us Section
    "about.page_title": "About Adinas Hospital",
    "about.meaning_text": "Adinas — a name built on trust, health, and compassionate care.",
    "about.meaning": "Meaning",
    "about.toc_title": "On This Page",
    "about.what_is_afilas": "What is Adinas Hospital",
    "about.what_is_afilas_p1": "Adinas General Hospital is a multi-specialty healthcare institution committed to providing exceptional medical services to the community.",
    "about.what_is_afilas_p2": "With a focus on patient-centered care, we combine advanced medical technology with compassionate service to ensure the best outcomes for every patient.",
    "about.what_is_afilas_p3": "Our hospital is dedicated to excellence in healthcare delivery, medical education, and community health initiatives.",
    "about.established": "Established",
    "about.established_year": "2024",
    "about.vision_title": "Vision",
    "about.vision_text": "To be the leading healthcare provider in Ethiopia, recognized for excellence in patient care, medical innovation, and community service.",
    "about.mission_title": "Mission",
    "about.mission_1": "To provide accessible, affordable, and high-quality healthcare services to all patients.",
    "about.mission_2": "To foster a culture of continuous learning and professional development among our staff.",
    "about.mission_3": "To embrace innovation and technology in healthcare delivery.",
    "about.mission_4": "To promote health and wellness through community engagement and education.",
    "about.core_values_title": "Our Core Values",
    "about.core_value_1_title": "Compassion",
    "about.core_value_1_desc": "We treat every patient with kindness, empathy, and genuine care.",
    "about.core_value_2_title": "Excellence",
    "about.core_value_2_desc": "We pursue the highest standards of medical practice and service delivery.",
    "about.core_value_3_title": "Integrity",
    "about.core_value_3_desc": "We uphold honesty, transparency, and ethical conduct in all operations.",
    "about.core_value_4_title": "Innovation",
    "about.core_value_4_desc": "We embrace modern medical technologies and continuously improve our processes.",
    "about.core_value_5_title": "Teamwork",
    "about.core_value_5_desc": "We work collaboratively to deliver comprehensive, patient-centered care.",
    "about.core_value_6_title": "Accountability",
    "about.core_value_6_desc": "We take responsibility for our actions and strive for measurable results.",

    // Footer
    "footer.tagline": "Elevating health through care and precision.",
    "footer.address": "Address: Addis Ababa, Ethiopia",
    "footer.phone": "Phone: +251 98 320 1998",
    "footer.email": "Email: info@adinashospital.com",
    "footer.quick_links": "Quick Links",
    "footer.hospital_departments": "Hospital Departments",
    "footer.careers_news": "Careers & News",
    "footer.emergency_support": "Emergency & Support",
    "footer.emergency_hotline": "Emergency Hotline: +251 98 320 1998",
    "footer.rights_reserved": "All Rights Reserved.",
    "footer.emergency_hotline_label": "Emergency Hotline",
    "footer.available_24_7": "24/7 Available",
    "footer.copyright": "© 2026 Adinas General Hospital.",
    "footer.privacy_policy": "Privacy Policy",
    "footer.terms_of_use": "Terms of Use",

    // Blog
    "blog.title": "Health & Medical Insights",
    "blog.subtitle": "Stay informed with the latest medical research and healthcare updates.",
    "blog.search_placeholder": "Search articles, research, tags...",
    "blog.filter_all": "All Articles",
    "blog.filter_categories": "Categories",
    "blog.read_more": "Read Article",
    "blog.published_on": "Published on",
    "blog.by_author": "By",
    "blog.views": "views",
    "blog.likes": "likes",
    "blog.comments": "comments",
    "blog.tags": "Tags",
    "blog.video_available": "Video Included",
    "blog.no_blogs_found": "No articles found matching your criteria.",
    "blog.clear_filters": "Clear Filters",
    "blog.leave_comment": "Leave a Comment",
    "blog.comment_placeholder": "Write your thought or question...",
    "blog.submit_comment": "Post Comment",
    "blog.back_to_blogs": "Back to Articles",
    "blog.featured": "Featured Article",

    // General Hospital Page
    "hospital.hero.book_btn": "Book Appointment",
    "hospital.hero.view_services_btn": "View Medical Services",
    "hospital.welcome.title": "Welcome to Adinas General Hospital",
    "hospital.welcome.desc": "Adinas General Hospital is a multi-specialty hospital committed to providing exceptional healthcare services.",
    "hospital.dept.badge": "Clinical Excellence",
    "hospital.dept.overlay_title_1": "World-Class Medical",
    "hospital.dept.overlay_title_2": "Departments",
    "hospital.dept.title": "Specialized Medical Departments",
    "hospital.dept.subtitle": "Our multidisciplinary teams deliver world-class medical outcomes using cutting-edge technologies.",
    "hospital.dept.cardiology.name": "Cardiology",
    "hospital.dept.cardiology.desc": "Heart and cardiovascular system care",
    "hospital.dept.pediatrics.name": "Pediatrics",
    "hospital.dept.pediatrics.desc": "Specialized care for children and infants",
    "hospital.dept.neurology.name": "Neurology",
    "hospital.dept.neurology.desc": "Brain and nervous system treatment",
    "hospital.dept.orthopedics.name": "Orthopedics",
    "hospital.dept.orthopedics.desc": "Bone and joint health management",
    "hospital.dept.emergency.name": "Emergency Medicine",
    "hospital.dept.emergency.desc": "24/7 emergency and trauma care",

    "hospital.amenity.main_title": "World-Class Hospital Amenities",
    "hospital.amenity.item1.title": "ICU / CCU",
    "hospital.amenity.item1.desc": "Intensive care units with advanced monitoring.",
    "hospital.amenity.item2.title": "Surgery Suites",
    "hospital.amenity.item2.desc": "Modern operating rooms.",
    "hospital.amenity.item3.title": "Diagnostic Center",
    "hospital.amenity.item3.desc": "Advanced imaging and laboratory services.",
    "hospital.amenity.item4.title": "Pharmacy",
    "hospital.amenity.item4.desc": "In-house pharmacy available 24/7.",
    "hospital.amenity.item5.title": "Blood Bank",
    "hospital.amenity.item5.desc": "Safe blood transfusion services.",
    "hospital.amenity.item6.title": "Emergency Room",
    "hospital.amenity.item6.desc": "24/7 emergency and trauma care.",

    "hospital.sec_services.title": "Our Medical Services",
    "hospital.sec_services.subtitle": "Services",
    "hospital.sec_services.price_label": "Price: ETB",
    "hospital.sec_services.duration_label": "Duration:",
    "hospital.sec_services.min_unit": "min",
    "hospital.sec_services.location_label": "Location:",
    "hospital.sec_services.default_location": "Adinas General Hospital",
    "hospital.sec_services.book_btn": "Book",
    "hospital.sec_services.view_all_btn": "View All Services",

    "hospital.sec_doc.title": "Meet Our Expert Doctors",
    "hospital.sec_doc.subtitle": "Highly qualified specialists dedicated to your health",
    "hospital.sec_doc.experience_label": "Experience",
    "hospital.sec_doc.yrs_suffix": "+ yrs",
    "hospital.sec_doc.available_label": "Available",
    "hospital.sec_doc.view_all_btn": "View All Doctors",

    // Services Page
    "services.hero.badge": "Complete Medical Care",
    "services.hero.title": "Our Healthcare Services",
    "services.hero.subtitle": "Explore our comprehensive range of specialized medical services.",
    "services.search.placeholder": "Search services by name or description...",
    "services.search.results_count": "services found",
    "services.search.clear": "Clear Search",
    "services.search.no_results": "No services match your search",
    "services.search.no_results_desc": "Try searching with a different term.",
    "services.search.showing_all": "Showing all available services",
    "services.stat.available": "24/7 Care Available",
    "services.stat.specialists": "50+ Medical Specialists",

    // Doctor Details Modal
    "doctors.modal.title": "Doctor Details",
    "doctors.modal.specialization": "Specialization",
    "doctors.modal.experience": "Experience",
    "doctors.modal.education": "Education & Qualifications",
    "doctors.modal.fee": "Consultation Fee",
    "doctors.modal.location": "Practice Location",
    "doctors.modal.contact": "Contact Information",
    "doctors.modal.schedule": "Weekly Schedule & Availability",
    "doctors.modal.book": "Book Appointment",
    "doctors.modal.close": "Close",
    "doctors.modal.active_status": "Active & Available",
    "doctors.modal.free_fee": "Standard Rate",

    // Theme & Account
    "nav.more": "More",
    "nav.sign_in": "Sign In",
    "nav.create_account": "Create Account",
    "nav.profile": "My Profile",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",

    // Payment
    "payment.verifying": "Verifying Payment...",
    "payment.pleaseWait": "Please wait while we confirm your transaction",
    "payment.success": "Payment Successful! 🎉",
    "payment.successMessage": "Your payment has been confirmed successfully.",
    "payment.failed": "Payment Failed ❌",
    "payment.failedMessage": "We could not verify your payment. Please try again.",
    "payment.noReference": "No transaction reference found",
    "payment.verificationFailed": "Payment verification failed",
    "payment.transactionId": "Transaction ID:",
    "payment.reference": "Reference:",
    "payment.amount": "Amount:",
    "payment.status": "Status:",
    "payment.returnHome": "Return to Home",
    "payment.viewAppointments": "View My Appointments",
    "payment.tryAgain": "Try Again",

    "nav.departments": "Departments",

    // Departments Page
    "departments.loading": "Loading Departments...",
    "departments.loading_message": "Please wait while we fetch the departments",
    "departments.error_title": "Something went wrong",
    "departments.error_message": "Could not load departments. Please try again later.",
    "departments.try_again": "Try Again",
    "departments.badge": "Medical Services",
    "departments.title": "Our Departments",
    "departments.subtitle": "Explore our specialized medical departments",
    "departments.empty_title": "No Departments Yet",
    "departments.empty_message": "Departments will appear here once added.",
    "departments.total": "Total",
    "departments.departments": "Departments",
    "departments.default_description": "department providing specialized care",
    "departments.learn_more": "Learn More",

    // Departments Detail Page
    "departments.back": "Back to Departments",
    "departments.back_to_all": "Back to All Departments",
    "departments.department": "Department",
    "departments.about": "About",
    "departments.providing_care": "department providing specialized medical care",
    "departments.about_description": "department provides comprehensive medical care for patients requiring specialized treatment.",
    "departments.not_found": "Department Not Found",
    "departments.not_found_message": "The department you're looking for doesn't exist.",
    "departments.services": "Our Services",
    "departments.service_1": "Specialized consultations",
    "departments.service_2": "Advanced diagnostics",
    "departments.service_3": "Treatment plans",
    "departments.service_4": "Follow-up care",
    "departments.hours": "Working Hours",
    "departments.weekdays": "Monday - Friday",
    "departments.saturday": "Saturday",
    "departments.sunday": "Sunday",
    "departments.closed": "Closed",
    "departments.emergency": "Emergency",
    "departments.contact_location": "Contact & Location",
    "departments.location": "Addis Ababa, Ethiopia",
    "departments.book_appointment": "Book Appointment",
  },

  am: {
    // Hospital Names
    "hospital.name.full": "አዲናስ ጠቅላላ ሆስፒታል",
    "hospital.name.short": "አዲናስ ሆስፒታል",
    "hospital.name.general": "ጠቅላላ ሆስፒታል",
    "hospital.name.adinas": "አዲናስ",
    "hospital.name.afilas": "አዲናስ",

    // Navigation & Topbar
    "nav.home": "መነሻ",
    "nav.hospital": "ሆስፒታል",
    "nav.about": "ስለ እኛ",
    "nav.contact": "ግንኙነት",
    "nav.service": "አገልግሎቶች",
    "nav.services": "አገልግሎቶች",
    "nav.blog": "ብሎግ",
    "nav.about_us": "ስለ እኛ",
    "nav.contact_emergency": "ግንኙነት እና ድንገተኛ",
    "nav.toggle_menu": "ማውጫ ቀይር",
    "topbar.emergency_available": "የድንገተኛ እንክብካቤ 24/7 ይገኛል",
    "topbar.call": "ይደውሉ:",
    "cta.emergency_call": "የድንገተኛ ጥሪ",
    "cta.book_appointment": "ቀጠሮ ይያዙ",

    "nav.selected": "ተመርጧል",
    "nav.menu": "ምናሌ",
    "nav.quick_links": "ፈጣን አገናኞች",
    "nav.doctors": "ሀኪሞች",
    "nav.account": "መለያ",
    "nav.login": "ግባ",
    "nav.register": "ተመዝገብ",
    "nav.book": "አስይዝ",
    "nav.book_services": "አገልግሎቶችን ያስይዙ",
    "nav.book_hospital_desc": "በአዲናስ ጠቅላላ ሆስፒታል ያስይዙ",
    "nav.book_appointment": "በአዲናስ ጠቅላላ ሆስፒታል ቀጠሮ ይያዙ",  // Added this line
    "nav.branch_links": "የቅርንጫፍ አገናኞች",

    // Hero Section
    "hero.headline": "እንኳን ወደ አዲናስ ጠቅላላ ሆስፒታል በደህና መጡ",
    "hero.subheadline": "ከፍተኛ ደረጃ ያለው የህክምና አገልግሎት እና ልዩ የህክምና አገልግሎቶች።",
    "hero.find_doctor": "ሐኪም ያግኙ",
    "hero.hospital_subtitle": "የ24 ሰዓት የታካሚ እንክብካቤ",
    "hero.welcome": "እንኳን ወደ አዲናስ ጠቅላላ ሆስፒታል በደህና መጡ",
    "hero.description": "ርህራሄ፣ ፈጠራ እና ልቀት ባለው ልዩ የጤና አገልግሎት ለመስጠት ቁርጠኞች ነን። የተሰጠ የህክምና ባለሙያዎች ቡድናችን ለእያንዳንዱ ታካሚ ከፍተኛ ጥራት ያለው እንክብካቤ ያረጋግጣል።",
    "hero.book_appointment": "ቀጠሮ ይያዙ",

    // General Hospital Section
    "general.title": "አዲናስ ጠቅላላ ሆስፒታል",
    "general.hospital": "ጠቅላላ ሆስፒታል",
    "general.subtitle": "ርህራሄ ያለው፣ ልዩ የታካሚ እንክብካቤ በ24/7 ይገኛል።",
    "general.feature1": "ከ10 በላይ ልዩ ልዩ የሕክምና ማዕከላት በአንድ ቦታ",
    "general.feature2": "ዘመናዊ የምርመራ እና የህክምና አገልግሎቶች",
    "general.feature3": "ምቹ የሆነ አንድ ቦታ ላይ የሚገኝ የሕክምና ማዕከል",
    "general.feature4": "ከፍተኛ ጥራት ያለው የግል ሆስፒታል",
    "general.feature5": "ልምድ ያላቸው የሕክምና ባለሙያዎች",
    "general.location": "አድራሻ",
    "general.location_address": "አዲስ አበባ፣ ኢትዮጵያ",
    "general.emergency_services": "የአደጋ ጊዜ አገልግሎት",
    "general.emergency_desc": "24/7 የአደጋ ጊዜ እንክብካቤ እና አምቡላንስ አገልግሎት",
    "general.cta": "አገልግሎቶቻችንን ያስሱ",
    "general.why_choose_us": "ለምን እኛን ይምረጡ?",
    "general.why_choose_1": "ከፍተኛ ልምድ ባላቸው ስፔሻሊስቶች የህክምና ልቀት።",
    "general.why_choose_2": "ሁሉን አቀፍ እንክብካቤ - ሙሉ የህክምና አገልግሎቶች።",
    "general.why_choose_3": "ዘመናዊ ቴክኖሎጂ - ዘመናዊ የህክምና መሳሪያዎች።",
    "general.why_choose_4": "በታካሚ ላይ ያተኮረ አቀራረብ - ርህራሄ ያለው፣ ግላዊ እንክብካቤ።",
    "general.why_choose_5": "24/7 ተገኝነት - የድንገተኛ እና ወሳኝ እንክብካቤ አገልግሎቶች።",
    "general.why_choose_6": "ከፍተኛ ጥራት ያላቸው መገልገያዎች - ዘመናዊ የታካሚ ክፍሎች እና ICUs።",
    "general.hospital_description": "ሆስፒታላችን ርህራሄ ያለው እና ልምድ ያለው የህክምና እንክብካቤ ለማህበረሰባችን ሲሰጥ ቆይቷል። የልቀት ቅርሳችን በልምድ፣ በፈጠራ እና ለታካሚ ደህንነት ባለን የማያቋርጥ ቁርጠኝነት ላይ የተገነባ ነው።",
    "general.learn_more": "ተጨማሪ ይወቁ",

    // Doctor Finder Section - Added Amharic translations
    "doctors.hero.badge": "ሐኪም ያግኙ",
    "doctors.hero.title": "የኛ ባለሙያ ሀኪሞች",
    "doctors.hero.subtitle": "በዋና ዋና የሕክምና ዘርፎች ውስጥ ልምድ ካላቸው ስፔሻሊስቶች ጋር ይገናኙ።",
    "doctors.headline": "ሐኪም ያግኙ",
    "doctors.subtitle": "በዋና ዋና የሕክምና ዘርፎች ውስጥ ልምድ ካላቸው ስፔሻሊስቶች ጋር ይገናኙ።",
    "doctors.filter_specialty": "ስፔሻሊቲ ይምረጡ",
    "doctors.filter_availability": "ተገኝነት ይምረጡ",
    "doctors.filter_search": "ሐኪም በስም ይፈልጉ...",
    "doctors.view_all": "ሁሉንም ስፔሻሊስቶች ይመልከቱ እና ቀጠሮ ይያዙ",
    "doctors.book": "ቀጠሮ ይያዙ",
    "doctors.email": "ኢሜይል",
    "doctors.available": "ይገኛል",
    "doctors.status_loading": "በመጫን ላይ...",
    "doctors.status_offline": "መስመር የለም!",
    "doctors.status_live": "የቀጥታ ውሂብ",
    "doctors.no_doctors": "ከመስፈርትዎ ጋር የሚስማማ ምንም ሐኪም አልተገኘም።",

    // About Us Section
    "about.page_title": "ስለ አዲናስ ሆስፒታል",
    "about.meaning_text": "አዲናስ — በመተማመን፣ በጤና እና በርህራሄ እንክብካቤ ላይ የተገነባ ስም።",
    "about.meaning": "ትርጉም",
    "about.toc_title": "በዚህ ገጽ ላይ",
    "about.what_is_afilas": "አዲናስ ሆስፒታል ምንድን ነው",
    "about.what_is_afilas_p1": "አዲናስ ጠቅላላ ሆስፒታል ለማህበረሰቡ ልዩ የህክምና አገልግሎቶችን ለመስጠት የተሰጠ የተለያዩ ልዩ ልዩ የህክምና ተቋም ነው።",
    "about.what_is_afilas_p2": "በታካሚ ላይ ያተኮረ እንክብካቤ ላይ በማተኮር፣ ዘመናዊ የህክምና ቴክኖሎጂን ከርህራሄ አገልግሎት ጋር በማጣመር ለእያንዳንዱ ታካሚ ምርጥ ውጤት እናረጋግጣለን።",
    "about.what_is_afilas_p3": "ሆስፒታላችን በህክምና አገልግሎት፣ በህክምና ትምህርት እና በማህበረሰብ ጤና ተነሳሽነቶች ላይ ለልቀት የተሰጠ ነው።",
    "about.established": "የተመሰረተ",
    "about.established_year": "2024",
    "about.vision_title": "ራዕይ",
    "about.vision_text": "በኢትዮጵያ መሪ የጤና አገልግሎት አቅራቢ ለመሆን፣ በታካሚ እንክብካቤ፣ በህክምና ፈጠራ እና በማህበረሰብ አገልግሎት ለልቀት እውቅና የተሰጠው።",
    "about.mission_title": "ተልዕኮ",
    "about.mission_1": "ለሁሉም ታካሚዎች ተደራሽ፣ ተመጣጣኝ እና ከፍተኛ ጥራት ያለው የጤና አገልግሎት መስጠት።",
    "about.mission_2": "በሰራተኞቻችን ዘንድ ቀጣይነት ያለው ትምህርት እና ሙያዊ እድገት ባህልን ማሳደግ።",
    "about.mission_3": "በጤና አገልግሎት አሰጣጥ ውስጥ ፈጠራን እና ቴክኖሎጂን መቀበል።",
    "about.mission_4": "በማህበረሰብ ተሳትፎ እና ትምህርት ጤናን እና ደህንነትን ማስተዋወቅ።",
    "about.core_values_title": "የኛ ዋና እሴቶች",
    "about.core_value_1_title": "ርህራሄ",
    "about.core_value_1_desc": "ሁሉንም ታካሚዎች በደግነት፣ በመተሳሰብ እና በእውነተኛ እንክብካቤ እናስተናግዳለን።",
    "about.core_value_2_title": "ልቀት",
    "about.core_value_2_desc": "ከፍተኛ ደረጃ ያላቸውን የህክምና ልምዶች እና የአገልግሎት አሰጣጥ እናከተላለን።",
    "about.core_value_3_title": "ታማኝነት",
    "about.core_value_3_desc": "በሁሉም ተግባራት ውስጥ ሐቀኝነትን፣ ግልጽነትን እና ሥነ ምግባራዊ ስነ ምግባርን እናስጠብቃለን።",
    "about.core_value_4_title": "ፈጠራ",
    "about.core_value_4_desc": "ዘመናዊ የህክምና ቴክኖሎጂዎችን እንቀበላለን እና ሂደቶቻችንን ያለማቋረጥ እናሻሽላለን።",
    "about.core_value_5_title": "የቡድን ስራ",
    "about.core_value_5_desc": "አጠቃላይ፣ በታካሚ ዙሪያ ያተኮረ እንክብካቤ ለመስጠት በትብብር እንሰራለን።",
    "about.core_value_6_title": "ተጠያቂነት",
    "about.core_value_6_desc": "ለድርጊቶቻችን ኃላፊነት እንወስዳለን እና ለሚለካ ውጤት እንጥራለን።",

    // Footer
    "footer.tagline": "በእንክብካቤ እና ትክክለኛነት ጤናን ማሳደግ።",
    "footer.address": "አድራሻ፡ አዲስ አበባ፣ ኢትዮጵያ",
    "footer.phone": "ስልክ፡ +251 98 320 1998",
    "footer.email": "ኢሜይል፡ info@adinashospital.com",
    "footer.quick_links": "ፈጣን አገናኞች",
    "footer.hospital_departments": "የሆስፒታል ክፍሎች",
    "footer.careers_news": "ስራዎች እና ዜናዎች",
    "footer.emergency_support": "ድንገተኛ እና ድጋፍ",
    "footer.emergency_hotline": "የድንገተኛ ጊዜ መስመር፡ +251 98 320 1998",
    "footer.rights_reserved": "ሁሉም መብቶች የተጠበቁ ናቸው።",
    "footer.emergency_hotline_label": "የድንገተኛ ጊዜ መስመር",
    "footer.available_24_7": "በ24 ሰዓት ይገኛል",
    "footer.copyright": "© 2026 አዲናስ ጠቅላላ ሆስፒታል።",
    "footer.privacy_policy": "የግላዊነት ፖሊሲ",
    "footer.terms_of_use": "የአጠቃቀም ደንቦች",

    // Blog
    "blog.title": "የጤና እና ህክምና ግንዛቤዎች",
    "blog.subtitle": "የቅርብ ጊዜ የህክምና ምርምር እና የጤና መረጃዎችን ይከታተሉ።",
    "blog.search_placeholder": "ጽሑፎችን፣ ምርምሮችን ይፈልጉ...",
    "blog.filter_all": "ሁሉም ጽሑፎች",
    "blog.filter_categories": "ምድቦች",
    "blog.read_more": "ጽሑፉን ያንብቡ",
    "blog.published_on": "የታተመበት",
    "blog.by_author": "በ",
    "blog.views": "እይታዎች",
    "blog.likes": "ወደድኩት",
    "blog.comments": "አስተያየቶች",
    "blog.tags": "ታጎች",
    "blog.video_available": "ቪዲዮ አለው",
    "blog.no_blogs_found": "ከመስፈርትዎ ጋር የሚስማማ ምንም ጽሑፍ አልተገኘም።",
    "blog.clear_filters": "ማጣሪያዎችን አጽዳ",
    "blog.leave_comment": "አስተያየት ይተዉ",
    "blog.comment_placeholder": "ሀሳብዎን ወይም ጥያቄዎን ይፃፉ...",
    "blog.submit_comment": "አስተያየት ላክ",
    "blog.back_to_blogs": "ወደ ጽሑፎች ተመለስ",
    "blog.featured": "ልዩ ጽሑፍ",

    // General Hospital Page
    "hospital.hero.book_btn": "ቀጠሮ ይያዙ",
    "hospital.hero.view_services_btn": "የሕክምና አገልግሎቶችን ይመልከቱ",
    "hospital.welcome.title": "እንኳን ወደ አዲናስ ጠቅላላ ሆስፒታል በደህና መጡ",
    "hospital.welcome.desc": "አዲናስ ጠቅላላ ሆስፒታል ልዩ የህክምና አገልግሎቶችን ለመስጠት የተሰጠ ሆስፒታል ነው።",

    "hospital.dept.badge": "ክሊኒካዊ ብቃት",
    "hospital.dept.overlay_title_1": "ዓለም አቀፍ ደረጃ ያላቸው የህክምና",
    "hospital.dept.overlay_title_2": "ክፍሎች",
    "hospital.dept.title": "ልዩ የህክምና ክፍሎች",
    "hospital.dept.subtitle": "የባለሙያ ቡድኖቻችን ዘመናዊ ቴክኖሎጂዎችን በመጠቀም ጥራት ያለው የህክምና ውጤት ያቀርባሉ።",
    "hospital.dept.cardiology.name": "ካርዲዮሎጂ (የልብ ህክምና)",
    "hospital.dept.cardiology.desc": "የልብ እና የደም ዝውውር ስርዓት እንክብካቤ",
    "hospital.dept.pediatrics.name": "ፔዲያትሪክስ (የህፃናት ህክምና)",
    "hospital.dept.pediatrics.desc": "ለህፃናት እና ለጨቅላ ህፃናት ልዩ እንክብካቤ",
    "hospital.dept.neurology.name": "ኒውሮሎጂ (የነርቭ ህክምና)",
    "hospital.dept.neurology.desc": "የአእምሮ እና የነርቭ ስርዓት ህክምና",
    "hospital.dept.orthopedics.name": "ኦርቶፔዲክስ (የአጥንት ህክምና)",
    "hospital.dept.orthopedics.desc": "የአጥንት እና የመገጣጠሚያ ጤና አስተዳደር",
    "hospital.dept.emergency.name": "የድንገተኛ ህክምና",
    "hospital.dept.emergency.desc": "የ24/7 የድንገተኛ እና የአደጋ ጊዜ ህክምና",

    "hospital.amenity.main_title": "ዓለም አቀፍ ደረጃ ያላቸው የሆስፒታል መገልገያዎች",
    "hospital.amenity.item1.title": "ጽኑ ህሙማን መከታተያ (ICU / CCU)",
    "hospital.amenity.item1.desc": "ከፍተኛ ደረጃ ያለው የጽኑ ህሙማን ክፍል",
    "hospital.amenity.item2.title": "የቀዶ ጥገና ክፍሎች",
    "hospital.amenity.item2.desc": "ዘመናዊ የቀዶ ጥገና ክፍሎች",
    "hospital.amenity.item3.title": "የምርመራ ማዕከል",
    "hospital.amenity.item3.desc": "ዘመናዊ የምስል እና ላብራቶሪ አገልግሎቶች",
    "hospital.amenity.item4.title": "ፋርማሲ",
    "hospital.amenity.item4.desc": "በ24 ሰዓት ክፍት የሆነ የውስጥ ፋርማሲ",
    "hospital.amenity.item5.title": "የደም ባንክ",
    "hospital.amenity.item5.desc": "ደህንነቱ የተጠበቀ የደም ልገሳ አገልግሎት",
    "hospital.amenity.item6.title": "የድንገተኛ ህክምና ክፍል",
    "hospital.amenity.item6.desc": "የ24/7 የድንገተኛ እንክብካቤ",

    "hospital.sec_services.title": "የእኛ የህክምና አገልግሎቶች",
    "hospital.sec_services.subtitle": "አገልግሎቶች",
    "hospital.sec_services.price_label": "ዋጋ፡ ETB",
    "hospital.sec_services.duration_label": "የሚወስደው ጊዜ፡",
    "hospital.sec_services.min_unit": "ደቂቃ",
    "hospital.sec_services.location_label": "ቦታ፡",
    "hospital.sec_services.default_location": "አዲናስ ጠቅላላ ሆስፒታል",
    "hospital.sec_services.book_btn": "ቀጠሮ ያዙ",
    "hospital.sec_services.view_all_btn": "ሁሉንም አገልግሎቶች ይመልከቱ",

    "hospital.sec_doc.title": "ባለሙያ ሀኪሞቻችንን ይወቁ",
    "hospital.sec_doc.subtitle": "ለጤናዎ የተሰጡ ከፍተኛ ብቃት ያላቸው ስፔሻሊስቶች",
    "hospital.sec_doc.experience_label": "ልምድ",
    "hospital.sec_doc.yrs_suffix": "+ ዓመታት",
    "hospital.sec_doc.available_label": "ይገኛል",
    "hospital.sec_doc.view_all_btn": "ሁሉንም ሀኪሞች ይመልከቱ",

    // Services Page
    "services.hero.badge": "ሙሉ የህክምና እንክብካቤ",
    "services.hero.title": "የጤና አገልግሎቶቻችን",
    "services.hero.subtitle": "የተለያዩ ልዩ የህክምና አገልግሎቶቻችንን ያስሱ።",
    "services.search.placeholder": "አገልግሎቶችን በስም ወይም በመግለጫ ይፈልጉ...",
    "services.search.results_count": "አገልግሎቶች ተገኝተዋል",
    "services.search.clear": "ፍለጋን አጽዳ",
    "services.search.no_results": "ከፍለጋዎ ጋር የሚስማማ ምንም አገልግሎት የለም",
    "services.search.no_results_desc": "በሌላ ቃል ለመፈለግ ይሞክሩ።",
    "services.search.showing_all": "ሁሉንም የሚገኙ አገልግሎቶች በማሳየት ላይ",
    "services.stat.available": "24/7 እንክብካቤ ይገኛል",
    "services.stat.specialists": "50+ የህክምና ባለሙያዎች",

    // Doctor Details Modal
    "doctors.modal.title": "የሀኪሙ ዝርዝር መረጃ",
    "doctors.modal.specialization": "የህክምና ሙያ",
    "doctors.modal.experience": "የስራ ልምድ",
    "doctors.modal.education": "ትምህርት እና ማስረጃ",
    "doctors.modal.fee": "የምክክር ክፍያ",
    "doctors.modal.location": "የስራ ቦታ",
    "doctors.modal.contact": "የግንኙነት መረጃ",
    "doctors.modal.schedule": "የሳምንቱ መርሃ ግብር",
    "doctors.modal.book": "ቀጠሮ ያዙ",
    "doctors.modal.close": "ዝጋ",
    "doctors.modal.active_status": "ዝግጁ እና ስራ ላይ ያለ",
    "doctors.modal.free_fee": "መደበኛ ክፍያ",

    // Theme & Account
    "nav.more": "ተጨማሪ",
    "nav.sign_in": "ይግቡ",
    "nav.create_account": "መለያ ይፍጠሩ",
    "nav.profile": "ፕሮፋይል",
    "nav.settings": "ቅንብሮች",
    "nav.logout": "ውጣ",
    "theme.light": "ብርሃን",
    "theme.dark": "ጨለማ",
    "theme.system": "ስርዓት",

    // Payment
    "payment.verifying": "ክፍያ በመፈተሽ ላይ...",
    "payment.pleaseWait": "እባክዎ ግብይትዎን እስክናረጋግጥ ድረስ ይጠብቁ",
    "payment.success": "ክፍያ ተሳክቷል! 🎉",
    "payment.successMessage": "ክፍያዎ በተሳካ ሁኔታ ተረጋግጧል።",
    "payment.failed": "ክፍያ አልተሳካም ❌",
    "payment.failedMessage": "ክፍያዎን ማረጋገጥ አልቻልንም።",
    "payment.noReference": "የግብይት ማጣቀሻ አልተገኘም",
    "payment.verificationFailed": "የክፍያ ማረጋገጫ አልተሳካም",
    "payment.transactionId": "የግብይት መታወቂያ፡",
    "payment.reference": "ማጣቀሻ፡",
    "payment.amount": "መጠን፡",
    "payment.status": "ሁኔታ፡",
    "payment.returnHome": "ወደ መነሻ ተመለስ",
    "payment.viewAppointments": "ቀጠሮዎቼን ይመልከቱ",
    "payment.tryAgain": "እንደገና ይሞክሩ",

    "nav.departments": "ክፍሎች",

    // Departments Page
    "departments.loading": "ክፍሎች በመጫን ላይ...",
    "departments.loading_message": "እባክዎ ክፍሎቹን እስክናመጣ ድረስ ይጠብቁ",
    "departments.error_title": "የሆነ ስህተት ተከስቷል",
    "departments.error_message": "ክፍሎቹን ማግኘት አልተቻለም።",
    "departments.try_again": "እንደገና ይሞክሩ",
    "departments.badge": "የህክምና አገልግሎቶች",
    "departments.title": "ክፍሎቻችን",
    "departments.subtitle": "ልዩ የህክምና ክፍሎቻችንን ያስሱ",
    "departments.empty_title": "እስካሁን ምንም ክፍሎች የሉም",
    "departments.empty_message": "ክፍሎች ከተጨመሩ በኋላ እዚህ ይታያሉ።",
    "departments.total": "ጠቅላላ",
    "departments.departments": "ክፍሎች",
    "departments.default_description": "ልዩ እንክብካቤ የሚሰጥ ክፍል",
    "departments.learn_more": "ተጨማሪ ይወቁ",

    // Departments Detail Page
    "departments.back": "ወደ ክፍሎች ተመለስ",
    "departments.back_to_all": "ወደ ሁሉም ክፍሎች ተመለስ",
    "departments.department": "ክፍል",
    "departments.about": "ስለ",
    "departments.providing_care": "ልዩ የህክምና እንክብካቤ የሚሰጥ ክፍል",
    "departments.about_description": "ልዩ ህክምና ለሚፈልጉ ታካሚዎች አጠቃላይ የህክምና እንክብካቤ ይሰጣል።",
    "departments.not_found": "ክፍል አልተገኘም",
    "departments.not_found_message": "የሚፈልጉት ክፍል የለም ወይም ተወግዷል።",
    "departments.services": "አገልግሎቶቻችን",
    "departments.service_1": "ልዩ ምክክሮች",
    "departments.service_2": "ዘመናዊ ምርመራዎች",
    "departments.service_3": "የህክምና እቅዶች",
    "departments.service_4": "ክትትል እንክብካቤ",
    "departments.hours": "የስራ ሰዓት",
    "departments.weekdays": "ሰኞ - አርብ",
    "departments.saturday": "ቅዳሜ",
    "departments.sunday": "እሁድ",
    "departments.closed": "ዝግ ነው",
    "departments.emergency": "ድንገተኛ",
    "departments.contact_location": "ግንኙነት እና አድራሻ",
    "departments.location": "አዲስ አበባ፣ ኢትዮጵያ",
    "departments.book_appointment": "ቀጠሮ ይያዙ",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem(
      "afilas-language",
    ) as Language | null;
    if (savedLanguage === "en" || savedLanguage === "am") {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("afilas-language", lang);
    } catch {
      // Ignore
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (context === undefined) {
    return {
      language: "en" as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }

  return context;
}